# Fase 1: Compila il progetto con Maven
FROM maven:3.8.7-eclipse-temurin-17 AS builder
WORKDIR /build
COPY . .
RUN mvn clean package -DskipTests

# Fase 2: Immagine finale minimal
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=builder /build/target/SiwBooks-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
