# Usa un'immagine base di Java 17 (adatta per Spring Boot)
FROM openjdk:17-jdk-slim

# Imposta la directory di lavoro dentro il container
WORKDIR /app

# Copia il file .jar dalla cartella target nel container
COPY target/*.jar app.jar

# Espone la porta su cui Spring Boot gira (di default: 8080)
EXPOSE 8080

# Comando per avviare l'app
ENTRYPOINT ["java", "-jar", "app.jar"]
